// <auto-generated />
using System;
using LocadoraDeFilmes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocadoraDeFilmes.Migrations
{
    [DbContext(typeof(LocadoraContext))]
    [Migration("20210609003947_filmes_update")]
    partial class filmes_update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LocadoraDeFilmes.Models.Filme", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("duracao")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<DateTime?>("lancamento")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("preco")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("sinopse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("filmes");
                });

            modelBuilder.Entity("LocadoraDeFilmes.Models.Locacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("dataHora")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int?>("filmeId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("filmeId");

                    b.ToTable("locacao");
                });

            modelBuilder.Entity("LocadoraDeFilmes.Models.Locacao", b =>
                {
                    b.HasOne("LocadoraDeFilmes.Models.Filme", "filme")
                        .WithMany()
                        .HasForeignKey("filmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("filme");
                });
#pragma warning restore 612, 618
        }
    }
}
